export * from './HomePage/HomePage'
export * from './SchedulePage/SchedulePage'
export * from './AnimePage/AnimePage'
export * from './ProfilePage/ProfilePage'
export * from './ProfilePage/ProfilePage'
export * from './RegisterPage/RegisterPage'
export * from './LoginPage/LoginPage'
